In [2]:
import numpy as np

In [14]:
xt = np.random.randn(3,10)
a_prev = np.random.randn(5,10)
Wy = np.random.randn(2,5)

In [30]:
concat=np.zeros([xt.shape[0]+Wy.shape[1],xt.shape[1]])
concat.shape

(8, 10)

In [25]:
concat

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
concat[: Wy.shape[1], :] = a_prev

In [27]:
concat

array([[-7.73558478e-01,  9.79411066e-01, -1.79554160e+00,
        -2.46110992e-01, -2.68481804e-01,  6.66814684e-02,
         3.53176914e-01,  1.36340913e+00,  3.17632907e-01,
        -4.99934755e-01],
       [-3.20859328e-01,  6.59640802e-01, -9.34676131e-01,
        -4.68924345e-01,  4.26948614e-01,  1.76964041e-03,
        -3.25837906e-01,  1.12382606e+00,  3.99565520e-02,
        -6.91987626e-01],
       [ 6.16342786e-01, -4.05655683e-01, -2.25150432e+00,
        -4.17245722e-01,  1.97176625e+00,  3.45788720e-01,
         1.25821059e-01, -6.01908257e-01, -4.68469071e-01,
         1.45173939e+00],
       [ 4.88375289e-01,  2.37250308e-01,  5.93245336e-01,
         4.40200668e-01, -9.75975045e-01,  8.32286920e-01,
        -9.04388118e-01,  2.31216232e+00,  7.43986967e-01,
         5.13476277e-01],
       [-3.11852993e-01, -8.02418828e-01, -9.69527512e-01,
        -7.07093103e-01, -5.49640281e-01,  8.21815966e-02,
        -8.97860863e-01,  1.35559836e+00, -5.33400662e-01,
         1.

In [28]:
concat[Wy.shape[1] :, :] = xt

In [29]:
concat

array([[-7.73558478e-01,  9.79411066e-01, -1.79554160e+00,
        -2.46110992e-01, -2.68481804e-01,  6.66814684e-02,
         3.53176914e-01,  1.36340913e+00,  3.17632907e-01,
        -4.99934755e-01],
       [-3.20859328e-01,  6.59640802e-01, -9.34676131e-01,
        -4.68924345e-01,  4.26948614e-01,  1.76964041e-03,
        -3.25837906e-01,  1.12382606e+00,  3.99565520e-02,
        -6.91987626e-01],
       [ 6.16342786e-01, -4.05655683e-01, -2.25150432e+00,
        -4.17245722e-01,  1.97176625e+00,  3.45788720e-01,
         1.25821059e-01, -6.01908257e-01, -4.68469071e-01,
         1.45173939e+00],
       [ 4.88375289e-01,  2.37250308e-01,  5.93245336e-01,
         4.40200668e-01, -9.75975045e-01,  8.32286920e-01,
        -9.04388118e-01,  2.31216232e+00,  7.43986967e-01,
         5.13476277e-01],
       [-3.11852993e-01, -8.02418828e-01, -9.69527512e-01,
        -7.07093103e-01, -5.49640281e-01,  8.21815966e-02,
        -8.97860863e-01,  1.35559836e+00, -5.33400662e-01,
         1.