In [1]:
import numpy as np

a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [16]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print("vectorized version:" +str(1000*(toc-tic)) +" ms")

c=0
tic=time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc=time.time()

print(c)
print("for loop version:" +str(1000*(toc-tic)) +" ms")


249894.81121245175
vectorized version:0.9729862213134766 ms
249894.81121245382
for loop version:327.1458148956299 ms


In [21]:
import math
n=100000
v=np.random.rand(1000000)
u=np.zeros((n,1))
tic=time.time()
for i in range (n):
    u[i]=math.exp(v[i])
toc=time.time()

print (u)
print("vectorized version:" +str(1000*(toc-tic)) +" ms")

[[1.16788691]
 [2.55600839]
 [2.28070859]
 ...
 [1.0695791 ]
 [1.93408517]
 [1.35158682]]
vectorized version:33.93435478210449 ms


In [23]:
import numpy as np
tic=time.time()
u=np.exp(v)
toc=time.time()
print (u)
print("vectorized version:" +str(1000*(toc-tic)) +" ms")

[1.16788691 2.55600839 2.28070859 ... 1.83544074 1.96388581 2.55276302]
vectorized version:1.992940902709961 ms
