In [3]:
import numpy as np

a=np.random.randn(5)
print(a)

[-1.0075852  -0.28675951  0.42515959  0.26298535  1.35111449]


rank 1 array

In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-1.0075852  -0.28675951  0.42515959  0.26298535  1.35111449]


In [6]:
print(np.dot(a,a.T))

3.1728912782704035


In [8]:
a=np.random.randn(5,1)
print(a)

[[-0.40628911]
 [ 1.07310438]
 [-0.86370404]
 [-0.65018251]
 [ 0.26537687]]


In [10]:
print(a.T)


[[-0.40628911  1.07310438 -0.86370404 -0.65018251  0.26537687]]


In [9]:
print(np.dot(a,a.T))

[[ 0.16507084 -0.43599062  0.35091354  0.26416207 -0.10781973]
 [-0.43599062  1.15155301 -0.92684459 -0.6977137   0.28477708]
 [ 0.35091354 -0.92684459  0.74598466  0.56156526 -0.22920707]
 [ 0.26416207 -0.6977137   0.56156526  0.42273729 -0.1725434 ]
 [-0.10781973  0.28477708 -0.22920707 -0.1725434   0.07042488]]


In [13]:
assert(a.shape ==(5,1))

In [14]:
a=a.reshape(1,5)
print(a)

[[-0.40628911  1.07310438 -0.86370404 -0.65018251  0.26537687]]


In [15]:
a=a.reshape(5,1)
print(a)

[[-0.40628911]
 [ 1.07310438]
 [-0.86370404]
 [-0.65018251]
 [ 0.26537687]]


In [18]:
a=a.reshape(1,5)
print(a)

[[-0.40628911  1.07310438 -0.86370404 -0.65018251  0.26537687]]
